### ISSUE TITLE
Doesn't work on replit.

### ISSUE THREAD

**Issue by gibran-mojica** [Brogames85-star/modmail-by-the-brogamer#2]
Everytime i try to start it, i get this error any help please?

internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'node:events'
Require stack:
- /home/runner/modmail-by-the-brogamer/node_modules/discord.js/src/client/BaseClient.js
- /home/runner/modmail-by-the-brogamer/node_modules/discord.js/src/index.js
- /home/runner/modmail-by-the-brogamer/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/modmail-by-the-brogamer/node_modules/discord.js/src/client/BaseClient.js:3:22)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/runner/modmail-by-the-brogamer/node_modules/discord.js/src/client/BaseClient.js',
    '/home/runner/modmail-by-the-brogamer/node_modules/discord.js/src/index.js',
    '/home/runner/modmail-by-the-brogamer/index.js'
  ]
}

**Comment by Brogames85-star** [comment]
Go to your shell on the right side of your screen and paste in this script:
npm i --save-dev node@lts && npm config set prefix=$(pwd)/node_modules/node && export PATH=$(pwd)/node_modules/node/bin:$PATH


Then make a .replit file in your Replit and add the following:
run = "npm start"


And finally, add the following into the package.json:
"scripts": {
  "start": "node index.js"
}
